name = "Poko"
author = "The-Simples"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13430dfbdf9bb65f694e46e48735c3ebb1854950a638362635c35387fbd04393"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
