name = "Poko"
author = "The-Simples"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c54442f91d6bc3936e6c265ce6152692e39c13e45d70b92fa4df2ff8b4589bd5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"
