name = "Poko"
author = "ahdg"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05c338438e7c27116fa696102a634a4d9ab744426c973a4a5f7ff980a642c366"

[versions]
minecraft = "1.18.2"
quilt = "0.17.7-beta.1"
