blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/The-Simples/poko/discussions
    about: General questions and support will be provided on the github Discussions.
