name: 🛠Setting change
description: Suggest an option/config/keybind/etc change in an existing mod or tool
labels: option
body:
- type: markdown
  attributes:
    value: |
      Before you request a config change, [please search](https://github.com/The-Simples/poko/issues) if it has already been requested and see [if it has already been changed](https://poko.vercel.app/config). 
      If it has been changed and you don't see it, make sure you are on the latest version and reset your settings.

- type: textarea
  attributes:
    label: What config to change
    description: Describe the change you want me to make.
  validations:
    required: true

- type: textarea
  attributes:
    label: Why should it be changed
    description: How can the change benefit everyone while keeping the experience "vanilla-like"?
  validations:
    required: true

- type: dropdown
  attributes:
    label: Category
    description: Select the type of change you request.
    multiple: false
    options:
      - Vanilla option
      - Mod config option
      - Changed keybind
      - Other
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional details
    description: Anything else you want to add?
  validations:
    required: false
